defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 1e4

checkpoint_frequency: 500

eval_frequency: 10000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 100
log_save_tb: true

# video recorder
save_video: true


seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
